/*
Copyright Arata Furukawa

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"context"
	"flag"
	"fmt"
	"path"

	"cuelang.org/go/cue/ast"
	cueastutil "cuelang.org/go/cue/ast/astutil"
	cueformat "cuelang.org/go/cue/format"
	"cuelang.org/go/cue/token"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/pluginpb"

	encodingcue "github.com/ornew/protoc-gen-cue/internal/encoding/cue"
	"github.com/ornew/protoc-gen-cue/pkg/options"
)

var (
	Version = "(unknown)"

	SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
)

// hasCuePackageOption checks if a proto file has the core.cue_package option set
func hasCuePackageOption(file *protogen.File) bool {
	fileOpts := file.Proto.GetOptions()
	if fileOpts == nil {
		return false
	}

	ext := proto.GetExtension(fileOpts, options.E_CuePackage)
	if ext == nil {
		return false
	}

	if cuePackage, ok := ext.(string); ok && cuePackage != "" {
		return true
	}

	return false
}

func main() {
	var flags flag.FlagSet
	_ = flags.String("root", ".", "")
	generateDefinedPackagesOnly := flags.Bool("generate_defined_packages_only", false, "only generate CUE for files with core.cue_package option set")
	protogen.Options{
		ParamFunc: flags.Set,
	}.Run(func(gen *protogen.Plugin) error {
		protocVersion := "(unknown)"
		if v := gen.Request.GetCompilerVersion(); v != nil {
			protocVersion = fmt.Sprintf("v%v.%v.%v", v.GetMajor(), v.GetMinor(), v.GetPatch())
			if s := v.GetSuffix(); s != "" {
				protocVersion += "-" + s
			}
		}
		gen.SupportedFeatures = SupportedFeatures
		cuegen := encodingcue.NewGenerator()
		genFiles := make(map[string]*protogen.File, len(gen.FilesByPath))
		for path, file := range gen.FilesByPath {
			cuegen.AddFile(path, file)
			if file.Generate {
				genFiles[path] = file
			}
		}
		ctx := context.Background()
		for filePath, file := range genFiles {
			// Skip files without core.cue_package option if generate_defined_packages_only is true
			if *generateDefinedPackagesOnly && !hasCuePackageOption(file) {
				continue
			}

			node, err := cuegen.GenerateFile(ctx, filePath)
			if err != nil {
				return fmt.Errorf("encode: %w", err)
			}
			node.AddComment(&ast.CommentGroup{
				Position: 0,
				List: []*ast.Comment{
					{Slash: token.Newline.Pos(), Text: "// Code generated by protoc-gen-cue. DO NOT EDIT."},
					{Slash: token.Newline.Pos(), Text: "// Versions:"},
					{Slash: token.Newline.Pos(), Text: "//     protoc-gen-cue: " + protocVersion},
					{Slash: token.Newline.Pos(), Text: "//     protoc:         " + Version},
					{Slash: token.Newline.Pos(), Text: "// Source: " + filePath},
				},
			})
			if err := cueastutil.Sanitize(node); err != nil {
				return fmt.Errorf("sanitize: %w", err)
			}
			b, err := cueformat.Node(node)
			if err != nil {
				return fmt.Errorf("format: %w", err)
			}

			// Construct filename using the original proto file path like pubsub generator does
			protoDir := path.Dir(file.Desc.Path())
			protoBase := path.Base(file.Desc.Path())
			// Remove .proto extension and add _gen.cue
			filenameBase := protoBase[:len(protoBase)-len(path.Ext(protoBase))]
			filename := protoDir + "/" + filenameBase + "_gen.cue"

			o := gen.NewGeneratedFile(filename, file.GoImportPath)
			_, err = o.Write(b)
			if err != nil {
				return fmt.Errorf("write: %w", err)
			}
		}
		return nil
	})
}
