//
//Copyright Arata Furukawa
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: cue.proto

package options

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          string                 `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	Default       string                 `protobuf:"bytes,2,opt,name=default,proto3" json:"default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_cue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_cue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_cue_proto_rawDescGZIP(), []int{0}
}

func (x *FieldOptions) GetExpr() string {
	if x != nil {
		return x.Expr
	}
	return ""
}

func (x *FieldOptions) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

var file_cue_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         230715,
		Name:          "cue.field",
		Tag:           "bytes,230715,opt,name=field",
		Filename:      "cue.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "cue.cue_package",
		Tag:           "bytes,50001,opt,name=cue_package",
		Filename:      "cue.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional cue.FieldOptions field = 230715;
	E_Field = &file_cue_proto_extTypes[0]
)

// Extension fields to descriptorpb.FileOptions.
var (
	// optional string cue_package = 50001;
	E_CuePackage = &file_cue_proto_extTypes[1]
)

var File_cue_proto protoreflect.FileDescriptor

const file_cue_proto_rawDesc = "" +
	"\n" +
	"\tcue.proto\x12\x03cue\x1a google/protobuf/descriptor.proto\"F\n" +
	"\fFieldOptions\x12\x17\n" +
	"\x04expr\x18\x01 \x01(\tB\x03\x88\x01\x01R\x04expr\x12\x1d\n" +
	"\adefault\x18\x02 \x01(\tB\x03\x88\x01\x01R\adefault:H\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\xbb\x8a\x0e \x01(\v2\x11.cue.FieldOptionsR\x05field:B\n" +
	"\vcue_package\x12\x1c.google.protobuf.FileOptions\x18ц\x03 \x01(\tR\n" +
	"cuePackage\x88\x01\x01B-Z+github.com/Bestowinc/protoc-gen-cue/pkg/optionsb\x06proto3"

var (
	file_cue_proto_rawDescOnce sync.Once
	file_cue_proto_rawDescData []byte
)

func file_cue_proto_rawDescGZIP() []byte {
	file_cue_proto_rawDescOnce.Do(func() {
		file_cue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cue_proto_rawDesc), len(file_cue_proto_rawDesc)))
	})
	return file_cue_proto_rawDescData
}

var file_cue_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cue_proto_goTypes = []any{
	(*FieldOptions)(nil),              // 0: cue.FieldOptions
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
	(*descriptorpb.FileOptions)(nil),  // 2: google.protobuf.FileOptions
}
var file_cue_proto_depIdxs = []int32{
	1, // 0: cue.field:extendee -> google.protobuf.FieldOptions
	2, // 1: cue.cue_package:extendee -> google.protobuf.FileOptions
	0, // 2: cue.field:type_name -> cue.FieldOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cue_proto_init() }
func file_cue_proto_init() {
	if File_cue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cue_proto_rawDesc), len(file_cue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_cue_proto_goTypes,
		DependencyIndexes: file_cue_proto_depIdxs,
		MessageInfos:      file_cue_proto_msgTypes,
		ExtensionInfos:    file_cue_proto_extTypes,
	}.Build()
	File_cue_proto = out.File
	file_cue_proto_goTypes = nil
	file_cue_proto_depIdxs = nil
}
